### ISSUE TITLE
脚手架初始化项目失败

### ISSUE THREAD

**Issue by Zhanghao0150** [Tencent/tdesign-vue-next-starter#250]
### tdesign-vue-next-starter 版本

v0.2.4

### 重现步骤

1,td-starter init
2,
?请输入项目名称： view
? 请输入项目描述： test
? 选择模板类型： 【Vue3】模板

### 期望结果

构建成功

### 实际结果

D:\work\packtool>td-starter init
*****************************
  _____   ____                 _                     ____    _                    _
 |_   _| |  _ \    ___   ___  (_)   __ _   _ __     / ___|  | |_    __ _   _ __  | |_    ___   _ __
   | |   | | | |  / _ \ / __| | |  / _` | | '_ \    \___ \  | __|  / _` | | '__| | __|  / _ \ | '__|
   | |   | |_| | |  __/ \__ \ | | | (_| | | | | |    ___) | | |_  | (_| | | |    | |_  |  __/ | |
   |_|   |____/   \___| |___/ |_|  \__, | |_| |_|   |____/   \__|  \__,_| |_|     \__|  \___| |_|
                                   |___/
*****************************

√ 构建环境正常！

? 请输入项目名称： view
? 请输入项目描述： Base on tdesign-starter-cli
? 选择模板类型： 【Vue3】模板
? 选择包含模块： 全部

👉  开始构建，请稍侯...

| 正在构建模板...
√ 构建成功！
write file error== Error: ENOENT: no such file or directory, open 'view\package.json'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at e.executeBuildSuccess (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tdesign-starter-cli\bin\index.js:2:29053)
    at e.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tdesign-starter-cli\bin\index.js:2:28474)
    at step (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:124:57)
    at fulfilled (C:\Users\Administrator\AppData\Roaming\npm\node_modules\tdesign-starter-cli\node_modules\tslib\tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'view\\package.json'
}

👏 初始化项目完成！👏

命令提示：
  # 进入项目
  $ cd ./view
  # 安装依赖
  $ npm install
  # 运行
  $ npm run dev

### 系统版本

Windows 11 21H2

### Node版本

v16.13.1

**Comment by Zhanghao0150** [comment]
又换了个目录和名字试了初始化，又可以构建了.
