### ISSUE TITLE
[TopPanel.vue] Initialize failed: invalid dom.

### ISSUE THREAD

**Issue by geekmister** [Tencent/tdesign-vue-next-starter#410]
### tdesign-vue-next-starter 版本

0.7.0

### 重现步骤

在Terminal中逐步输入一下命令：

1、td-starter init（Bug应该跟下面内容无关，贴一下供排除判断）
```
  请输入项目名称： temp
  请输入项目描述： temp
  选择模板类型：  【Vue3】模板
  生成代码版本：   通用模板版本
  选择包含模块：   全部
```

2、npm install

3、npm run dev

在浏览器中查看页面，具体情况请详见实际结果...

### 期望结果

正常打开 `http://localhost:3002/dashboard/base` 地址的页面...

### 实际结果

无法打开页面，页面空白，如下：
![image](https://user-images.githubusercontent.com/45185145/216798876-cb80198f-7bc6-400f-b428-976775c2467e.png)

报错信息：

```
Error: Initialize failed: invalid dom.
    at Module.init2 (echarts.js:2210:13)
    at renderMoneyChart (TopPanel.vue:85:24)
    at renderCharts (TopPanel.vue:101:3)
    at TopPanel.vue:125:3
    at runtime-core.esm-bundler.js:2757:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2731:29)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:359:32)
    at flushJobs (runtime-core.esm-bundler.js:413:9)
```

### 框架版本

Vue(^3.2.45)

### 浏览器版本

Chrome(109.0.5414.119)

### 系统版本

MacOS(11.7.3)

### Node版本

v16.16.0

**Comment by timi137137** [comment]
清空缓存在开...

**Comment by geekmister** [comment]
> 清空缓存在开...

感谢帮助，清空缓存后可以正常打开了:grinning:
