### ISSUE TITLE
刚刚创建的项目就报错啦！

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next-starter#628]
### tdesign-vue-next-starter 版本

0.9.0

### 重现链接

无

### 重现步骤

`td-starter init` 或者`git clone`项目到本地后`cnpm install -S `
然后`npm run dev`
页面白屏，查看控制台中报错
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/2550216/712eea6d-2595-4f25-b5fa-109a2dedd670)

### 期望结果

能正常运行不报错

### 实际结果

报错
```
vue-router.mjs:3471 Error: Initialize failed: invalid dom.
    at Module.init2 (echarts.js:2210:13)
    at renderMoneyChart (TopPanel.vue:111:24)
    at renderCharts (TopPanel.vue:127:3)
    at TopPanel.vue:151:3
    at runtime-core.esm-bundler.js:2741:88
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2721:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:330:40)
    at flushJobs (runtime-core.esm-bundler.js:368:5)
```

### 框架版本

vue 3.2.0

### 浏览器版本

Chrome 版本 118.0.5993.118（正式版本） （64 位）

### 系统版本

Windows 10

### Node版本

20.2.0

### 补充说明

无

**Comment by timi137137** [comment]
cnpm安装了一个错误的echarts版本，请使用其他包管理器或者手动降级，在package.json中我们强制限定了该包使用的版本
